### ISSUE TITLE
Could we remove collective.indexing

### ISSUE THREAD

**Issue by toutpt** [collective/dexterity.membrane#10]
Collective.indexing goal is to improve performance by change the way Plone's catalog is working. It has nothing to do with membrane.

This is not a dependency but it's better to use because membrane use a lot the catalog. So I believe this is a project decision to use collective.indexing but not an addon decision.

With the version 2.0 of indexing there is not anymore issues while removing it.

I have tagged this issue with question because I want opinion. And with bug because this is not a dependency.

**Comment by agitator** [comment]
c.indexing was merged into Plone 5.1 and dx.membrane is updated to work with 5.1
