### ISSUE TITLE
Fix username support

### ISSUE THREAD

**Issue by petri** [collective/dexterity.membrane#19]
Currently, if `use_email_as_username` registry setting is set to `False`, anything that is based on `DxUserObject` but does not provid a `username` attribute, will fail: see [line 81](https://github.com/collective/dexterity.membrane/blob/petri-fix-group/dexterity/membrane/behavior/user.py#L81) of DxUserObject class implementation.

As such, the bug affects also the example `Member` type that is provided by this package.

Assuming there are no downsides I've missed, I'll submit a PR containing:
- additional IUserName schema (with just the username field)
- modified IMember that inherits from IUsername (in addition to IEmail)

**Comment by gyst** [comment]
To further complicate matters, the ``username`` field is actually used to store the ``userid``. See #26.

**Comment by mauritsvanrees** [comment]
I have released dexterity.membrane 1.2 with the fix from Guido.
