### ISSUE TITLE
KeyError on membranepassword.IProvidePasswords

### ISSUE THREAD

**Issue by mikejmets** [collective/dexterity.membrane#23]
I upgraded a site to plone 4.3.10 and dex.membrane 1.1.1 and changed all references to IProvidePasswords in a local addon from membranepassword to password. If I create a new object that refers to a membrane actor it works fine but when I modify an existing object that refers to a membrane actor I get a key error on save.
...
*  Module zc.relation.catalog, line 556, in unindex_doc
*  Module zc.relation.catalog, line 621, in _remove
KeyError: <class 'dexterity.membrane.behavior.membranepassword.IProvidePasswords'> 

I don't see any upgrade steps in d.membrane. I did rebuild the catalog and tried a few other trick to no avail. Is there an upgrade step that I'm missing? As a workaround, I created a fork with an import of IProvidesPasswords from password in membranepassword.

**Comment by mauritsvanrees** [comment]
Yet another victim of this bug in z3c.relationfield:
https://github.com/zopefoundation/z3c.relationfield/issues/4

**Comment by mauritsvanrees** [comment]
Fixed in release 1.1.2.
