### ISSUE TITLE
Option to create a member content type object from the Users and Groups controlpanel

### ISSUE THREAD

**Issue by b4oshany** [collective/dexterity.membrane#32]
I noticed that when I add a new user via Users and Group control panel, there's no dexterity Member object created. 

![image](https://user-images.githubusercontent.com/1830494/34703303-32d0aa22-f4c0-11e7-81d3-3c29d42d31f7.png)

This will a problem for sites that allows their users to self-registered.
![image](https://user-images.githubusercontent.com/1830494/34703342-5c30c780-f4c0-11e7-8ddf-e7e33a9df869.png)

Therefore, we need bi-directional creation for the Member and User objects, i.e.
* Add Member -> Add User
* Add User -> Add Member

### My Hack

For the site I'm working on, I created a form and authorized the unauthorized creation of my `dexterity.membrane.JaDMember` and override the http://plone.site/register view with the form for JaDMember, which is open to anyone.
```
        with api.env.adopt_roles('Manager'):
            api.content.create(
                type='dexterity.membrane.JaDMember',
                container=portal,
                id=name,
                first_name=first_name,
                last_name=last_name,
                email=data.get("email"),
                password=data.get("password"),
                safe_id=True
            )
```
I don't like this solution because it might introduce security issues.

### Possible Solution

* Add an event listener for user objects that will create the Member object if the Id does not exist
* Add an option for existing users to generate their Member object after registration

***
User  =  Plone user
Member  =  Dexterity content type that is based on a Plone user 
***

**Comment by agitator** [comment]
Not sure ...
Wasn't it the basic concept to not link those directly?
I have a bunch of sites, where membrane users are seen as the "consumers" and plone users are more staff users that more act as reviewers and managers of those sites.
Self registration in this case creates membrane users.

**Comment by b4oshany** [comment]
The setup I have does not create membrane user via self-registration.  I
believe I did a basic setup.

Note, when I said Plone User, I didn't mean to include the role of the
user, but a member account.

**Comment by b4oshany** [comment]
I find the problem... I didn't enable use email as login under the security controlpanel
