### ISSUE TITLE
Accidentally pushed commits

### ISSUE THREAD

**Issue by djowett** [collective/dexterity.membrane#43]
Sorry! I just saw I accidentally pushed commits to this repo.... I must have been half asleep!! What's the best way of reversing them?  @mauritsvanrees ?

**Comment by ale-rt** [comment]
Hi @djowett, you can `git revert $COMMITHASHES` and then make a PR.

To get the commit hashes to revert use `git log`.

Anyway this should work: 
`git revert e4d5df70409a8f9c9328ea693da41a853a1f33c2 ca0f652aa2dcba67c8e92e741d27ac1830759158`

**Comment by djowett** [comment]
Thanks @ale-rt - that's in progress now  (my main question was more how much to clean up - but I understand from your answer that reverts are sufficient)
