### ISSUE TITLE
Python 3 compatibility

### ISSUE THREAD

**Issue by ksuess** [collective/dexterity.membrane#49]
Does dexterity.membrane already support Python 3? @ale-rt you were working on this, can you tell what is the current status?

**Comment by ale-rt** [comment]
We have a Python3 site which is happily using:
```
dexterity.membrane = git git@github.com:collective/dexterity.membrane.git branch=plone52
Products.membrane = git git@github.com:collective/Products.membrane.git branch=plone52
```
Actually it works better than before because first we had some troubles with group membership when the group title had unicode characters in it :)

**Comment by ale-rt** [comment]
The plone52 branches have been merged, i.e. this should work.
```
dexterity.membrane = git git@github.com:collective/dexterity.membrane.git branch=plone52
Products.membrane = git git@github.com:collective/Products.membrane.git branch=plone52
```
I will soon ask for an egg release of both.

**Comment by dodaiti** [comment]
Hello,
I want to use dexterity,membrane with Python3.
I used the two lines that @ale-rt mentioned in his last comment in my buildout.cfg but I got some right issues:
….
mr.developer: Cloned 'Products.membrane' with git using branch 'plone52' from 'git@github.com:collective/Products.membrane.git'.
mr.developer: git cloning of 'Products.membrane' failed.
mr.developer: git@github.com: Permission denied (publickey).
mr.developer: fatal: Could not read from remote repository.
mr.developer: Please make sure you have the correct access Rights

mr.developer: and the repository exists.
mr.developer: 
mr.developer: Cloned 'dexterity.membrane' with git using branch 'plone52' from 'git@github.com:collective/dexterity.membrane.git'.
mr.developer: git cloning of 'dexterity.membrane' failed.
mr.developer: Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
mr.developer: git@github.com: Permission denied (publickey).
mr.developer: fatal: Could not read from remote repository.
mr.developer: 
mr.developer: Please make sure you have the correct access rights
mr.developer: and the repository exists.
….

Could you please help me? Thank you.

**Comment by ksuess** [comment]
Just use master branches
```
dexterity.membrane = git https://github.com/collective/dexterity.membrane.git
Products.membrane = git https://github.com/collective/Products.membrane.git
```
Master of both do support Python 3
Releases for both packages are not yet done. Maybe @ale-rt or @mauritsvanrees can do this, they are maintainers of the packages.

**Comment by ale-rt** [comment]
They are actually released as prerelease versions:
- https://pypi.org/project/Products.membrane/5.0.0a1/
- https://pypi.org/project/dexterity.membrane/3.0.0a1/

Try to add to the buildout versions section:
```
Products.membrane = 5.0.0a1
dexterity.membrane = 3.0.0a1
```
I am using these pins since quite a while and will probably do a final release soon.

**Comment by dodaiti** [comment]
thank you @ksuess, the Installation worked now 👍

**Comment by dodaiti** [comment]
and thanks to @ale-rt also 👍

**Comment by ale-rt** [comment]
Then I would say this can be closed
