### ISSUE TITLE
Security

### ISSUE THREAD

**Issue by avoinea** [collective/dexterity.membrane#53]
I don't think this should be accessible via URL:

[
![2020-04-01-131037_562x113_scrot](https://user-images.githubusercontent.com/323385/78125846-47280c00-741a-11ea-9c8d-fab7a93a4d64.png)
](url)

**Comment by ale-rt** [comment]
@avoinea which version are you using? I was not able to replicate the issue on master.

**Comment by petschki** [comment]
Using `dexterity.membrane=3.0.0` here ... I cannot reproduce this.

**Comment by avoinea** [comment]
:smile: I don't remember where I used this add-on. Thus, it may be fixed by now.
